### ISSUE TITLE
Logging state_changed to events table every 30 seconds

### ISSUE THREAD

**Issue by clboles** [vanstinator/raincloudy#23]
Thanks for integrating RainCloud with Home Assistant.  The integration has been working great for me so far.

My Home Assistant db was growing quite fast, so I looked in the events table and found that it is logging state_changed events for all of the many raincloud sensors (x4 since there are four zones) every 30 seconds.  I've excluded most of the sensors from being recorded (battery, time left, rain delay, etc) since I don't really need to see those in the history.  I would like to keep the sensor for each zone_#_watering so I can see when each zone ran.

Would it be possible to only record events when the state actually changes (watering off -> on, etc) rather than polling and recording the values every 30 seconds?

**Comment by tchellomello** [comment]
@clboles  what you can do is on your `raincloud` base component (located at `configuration.yaml`), you can set the `scan_interval` to a higher number in seconds. That will set the frequency the `raincloudy` sensors will be updated. 

I ran a quick test on my environment and I got a similar behavior that you explained. 

```sql
sqlite> select state_id, state, attributes, last_changed, last_updated from states where entity_id = 'binary_sensor.grass_2_watering' order by last_updated ASC LIMIT 10 ;
2974620|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:39 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:39:19.421867
2974960|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:40 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:40:02.359302
2975139|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:41 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:41:05.160325
2975301|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:42 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:42:07.834011
2975428|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:43 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:43:11.381109
2975598|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:44 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:44:27.684588
2975704|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:45 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:45:15.933819
2975830|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:46 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:46:17.972262
2975954|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:47 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:47:20.071161
2976044|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "02:48 AM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-16 06:39:19.421867|2018-05-16 06:48:02.651434
```

If you look at the SQL above, the last_changed field kept the same value, however, the attributes changed because it's adding the timestamp (`current_time`) which might be triggering the update in the database. 

Maybe we can drop the attribute `current_time` from the Raincloud sensors which might help it.  I'll run a few tests on my environment and I'll let you know if that addresses the situation.

**Comment by tchellomello** [comment]
@clboles, I've modified the component on my personal HA instance and I'll keep monitoring. 

https://github.com/tchellomello/home-assistant/commit/20894aa4131a10142ce22ea7748cdaf80b0d7573

I'll check later tonight and if that does the tricky I'll be happy to submit a new PR to get this fixed.

**Comment by clboles** [comment]
I also noticed that the only column changing most of the time was the timestamp.  I'll play around with the scan interval and see if it helps.  In a perfect world, it would scan every 30s (or 1min), but only record the state change if something actually changed.  That way it would still detect the watering cycles quickly and accurately, but not flood the db.

On a related note, I'm hoping to make sun.sun stop scanning every 30s as well, but i'd still like to have the sun data recorded at least once per day.  The scan interval may be the ideal solution for that particular entity.

Thanks!

**Comment by tchellomello** [comment]
https://www.home-assistant.io/components/history/
```
attributes: JSON of the state attributes
last_changed: timestamp last time the state has changed. A state_changed event can happen when just attributes change.
last_updated: timestamp anything has changed (state, attributes)

```
So saving the `current_time` is not a good idea for sure.

**Comment by tchellomello** [comment]
@clboles  yes, much better now :) 

```sql
sqlite> select state_id, state, attributes, last_changed, last_updated from states where entity_id = 'binary_sensor.grass_2_watering' and last_updated > ('2018-05-19') order by last_updated DESC LIMIT 5;
3933011|off|{"attribution": "Data provided by Melnor Aquatimer.com", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-21 16:37:39.041561|2018-05-21 16:37:39.041561
3932882|on|{"attribution": "Data provided by Melnor Aquatimer.com", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water"}|2018-05-21 16:36:10.707262|2018-05-21 16:36:10.707262
3931810|off|{"attribution": "Data provided by Melnor Aquatimer.com", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-21 16:30:09.057418|2018-05-21 16:30:09.057418

-- after change ^

3931489|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "12:24 PM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-17 06:08:06.510727|2018-05-21 16:24:03.542553
3931371|off|{"attribution": "Data provided by Melnor Aquatimer.com", "current_time": "12:23 PM", "identifier": 2, "unit_of_measurement": "", "friendly_name": "Grass #2 Watering", "icon": "mdi:water-off"}|2018-05-17 06:08:06.510727|2018-05-21 16:23:01.242666
```

Update frequency resolved. I'll submit a PR tonight. Thanks for the heads up @clboles :+1:

**Comment by clboles** [comment]
That's great.  Thanks!

**Comment by tchellomello** [comment]
@clboles  PR submitted to HA https://github.com/home-assistant/home-assistant/pull/14584

I'm going ahead and closing this since we can track that directly on HA issues now. 

Thanks for reporting this problem!!
