### ISSUE TITLE
Examples in Usage Not Working

### ISSUE THREAD

**Issue by kq9914** [vanstinator/raincloudy#28]
The examples at the bottom of the usage portion of readme are not working.  The syntax used in the examples has an underscore rather than a dot after the zone identifier:
`raincloudy.controller.faucet.zone2_watering_time = 5`
when it should be:
`raincloudy.controller.faucet.zone2.watering_time = 5`

**Comment by tchellomello** [comment]
Many thanks for reporting this issue @kq9914 !! :+1:
