### ISSUE TITLE
Publish 0.0.7 to PyPi

### ISSUE THREAD

**Issue by vanstinator** [vanstinator/raincloudy#35]
@tchellomello Please publish another bugfix release to PyPi off master so I can include them in Home Assistant :) 

Thanks!

**Comment by tchellomello** [comment]
@vanstinator  I'll do it shortly!

@vanstinator  what is your pypi id so I can grant you permissions to push to PyPi too. 

teamwork++

**Comment by vanstinator** [comment]
Awesome! And I just made an account this morning :) Username over there should be `vanstinator` as well.

Thanks for the quick turnaround!

**Comment by tchellomello** [comment]
@vanstinator just granted you privileges. If you want to do it, go for it. If not, I might take a look around noon (EST) today.

**Comment by vanstinator** [comment]
Doesn't look like I actually have rights to publish anything. 

![2019-04-09 11_04_13-PyPI](https://user-images.githubusercontent.com/577219/55811514-3d91ef80-5ab7-11e9-9057-2632657345fa.png)

**Comment by vanstinator** [comment]
Ah it's a CLI thing isn't it. Found some docs. Will give it a go!
