### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by eniak11** [vanstinator/raincloudy#46]
I got this error in login:

SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Then I manually added wifiaquatimer_com_chain.cer to a file, ca-bundle.crt, my CA store in Windows and its path to pip.ini. Still same error. Thank you for the help!

**Comment by vanstinator** [comment]
This was fixed in 0.0.9

**Comment by eniak11** [comment]
I just realized I installed 1.0a1. I removed it and installed 1.0a2. No more login error. Thank you very much!

**Comment by vanstinator** [comment]
I released 1.0.0 yesterday.

**Comment by eniak11** [comment]
Sounds good. Thank you again!
